name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: sbt coverage test coverageReport
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v3"
        with:
          fail_ci_if_error: true
      - name: Build typescript
        run: |
          npm --prefix ts build
          cp ts/dist/payment.js public/javascripts/
          sbt dist
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
