name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: sbt coverage test coverageReport
      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::715102664058:role/GithubDeployPianoLessonsToECR
          aws-region: eu-west-2
          role-session-name: ECRLogin
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v3"
        with:
          fail_ci_if_error: true
      - name: Build typescript
        run: |
          npm --prefix ts ci
          npm --prefix ts run build
          mkdir public/javascripts
          cp ts/dist/payment.js public/javascripts/
          sbt dist 
          docker build -t 715102664058.dkr.ecr.eu-west-2.amazonaws.com/piano-lessons
          docker push 715102664058.dkr.ecr.eu-west-2.amazonaws.com/piano-lessons
