name: Test

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Scala tests
        run: sbt test scalafmtCheckAll
      - name: Run Typescript tests
        run: |
          cd ts
          npm ci
          npm run checks
